spring:
  application:
    name: config-client
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
      username: ${datasource.username}
      password: ${datasource.password}
      driverClassName: com.mysql.jdbc.Driver

server:
  port: 9030