info:
  profile: default
  from: git-config-repo

datasource:
  password: {cipher}AIAGanYUUkmLt//Y3g9ZUmxwUPXAmWILoUPpZo5bm1PEfEytr+dQ10HTH0//PGuVu+ZnxEUNfaPN/na7XGIrVTnmMjX1zaPiZxs32oR5zoRrYEnAMFveisIHWOSSZ1bmAhAuvUK/QwiTXgGrwmGKhw9aj/ltaoglWdRO+p9UcE5admNUV/Iiqer8HlyN405aj1WALEqj+PvDN3OsLPFVNitb